apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jo0q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jo0q
    app.kubernetes.io/part-of: tkrw-pr712-0075-0071-app
  name: devfile-sample-jo0q
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jo0q
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jo0q
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-jo0q@sha256:dd0c74635caf7968d6a08e5dcae4e98fb760a5034c01a1236bb93a25a0ecdb5f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
